# Generated by Django 2.0.5 on 2018-05-08 13:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('traffic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('Broken', 'Broken'), ('Danger', 'Danger'), ('Incident', 'Incident'), ('Info', 'Info'), ('Warning', 'Warning')], default=1, max_length=40),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 8, 13, 40, 34, 331181, tzinfo=utc)),
        ),
    ]
