# Generated by Django 2.0.5 on 2018-05-08 20:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('traffic', '0002_auto_20180508_0940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 8, 20, 17, 57, 812031, tzinfo=utc)),
        ),
    ]
